### ISSUE TITLE
Getting path error when opening PGCli with Sublime REPL

### ISSUE THREAD

**Issue by gstoffer** [darikg/PgcliSublime#3]
Hello,

I have the following error when I try to open pgcli with sublime repl : 

Traceback (most recent call last):
  File "/home/user/.config/sublime-text-3/Packages/SublimeREPL/sublimerepl.py", line 487, in open
    r = repls.Repl.subclass(type)(encoding, **kwds)
  File "pgcli_sublime_repl in /home/user/.config/sublime-text-3/Installed Packages/PgcliSublime.sublime-package", line 24, in **init**
  File "/home/user/envs/pgcli/lib/python3.3/site-packages/pgcli/main.py", line 87, in **init**
    write_default_config(default_config, pgclirc_file)
  File "/home/user/envs/pgcli/lib/python3.3/site-packages/pgcli/config.py", line 22, in write_default_config
    destination = expanduser(destination)
  File "./posixpath.py", line 252, in expanduser
AttributeError: 'NoneType' object has no attribute 'startswith'
error: AttributeError("'NoneType' object has no attribute 'startswith'",)

Could you tell me how to fix it, please ? :-)

My environment : 
SublimeText 3 (build 3103)
Virtualenv with python 3.3
Sublime REPL 2.1.2

regards,

Guillaume Stoffer

**Comment by darikg** [comment]
Hi Guillaume,

I fell behind in keeping PgcliSublime up to date with pgcli. I just updated PgcliSublime and got the repl working again. Could you update and try again?

**Comment by gstoffer** [comment]
Hi Darik,

PgCliSublime works fine after the update. :-)

Thanks a lot !
